import * as bcrypt from 'bcryptjs';
import * as jwt from 'jsonwebtoken';
import { User } from '@prisma/client'; // Import the User type generated by Prisma

// --- Configuration ---
// We access the secret key directly from process.env, 
// which is loaded from the .env.local file.
// IMPORTANT: This should be configured to throw an error if the secret is missing in production.
const JWT_SECRET = process.env.JWT_SECRET || 'fallback_secret_for_development_only'; 


// --- 1. Password Utilities (bcryptjs) ---

/**
 * Hashes a plain-text password for secure storage in the database.
 * @param password The plain-text password string.
 * @returns The hashed password string.
 */
export async function hashPassword(password: string): Promise<string> {
  const salt = await bcrypt.genSalt(10); // Generate a salt (recommended 10-12 rounds)
  return bcrypt.hash(password, salt);
}

/**
 * Compares a plain-text password submitted by the user with a hashed password from the database.
 * @param password The plain-text password submitted by the user.
 * @param hash The hashed password stored in the database.
 * @returns True if the passwords match, false otherwise.
 */
export async function comparePassword(password: string, hash: string): Promise<boolean> {
  return bcrypt.compare(password, hash);
}


// --- 2. JWT Utilities (jsonwebtoken) ---

// Define the payload structure for type safety, using the User type from Prisma
// We only need the userId in the token to identify the user later.
export interface JwtPayload {
  userId: string;
}

/**
 * Generates a JSON Web Token (JWT) for a user upon successful login.
 * @param user The User object returned by Prisma.
 * @returns The signed JWT string.
 */
export function generateToken(user: User): string {
  const payload: JwtPayload = { userId: user.id };

  // Signs the token using the secret key and sets an expiration time
  return jwt.sign(
    payload,
    JWT_SECRET,
    { expiresIn: '1d' } // Token expires in 1 day (common practice for short-lived access tokens)
  );
}

/**
 * Verifies a JWT and extracts the payload.
 * @param token The JWT string provided by the client (usually from the Authorization header).
 * @returns The verified payload (userId) or null if verification fails.
 */
export function verifyToken(token: string): JwtPayload | null {
  try {
    // The 'as JwtPayload' assertion uses TypeScript to ensure the result matches our expected type
    const verified = jwt.verify(token, JWT_SECRET) as JwtPayload;
    return verified;
  } catch (error) {
    // This catches errors like 'TokenExpiredError' or 'JsonWebTokenError' (invalid signature)
    return null;
  }
}